  jobs:
  test:
    docker:      
      - image: chandrarai/pythonapp:latest      

    steps:
      - checkout      
             
      - store_artifacts:
           path: .
           destination: test_output
             
  dockerize:
    machine: true
    steps:
      - checkout

      # Login to docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: docker build -t $DOCKER_USER/cir_testapp:$CIRCLE_SHA1 .

      # deploy the image
      - run: docker push $DOCKER_USER/cir_testapp:$CIRCLE_SHA1
  
  deploy:
    machine: true
    steps:
      - checkout

      - run: docker run -p 8888:5000 --name cir_testapp chandrarai/cir_testapp
      
  workflows:
  version: 2
  test_build:
      jobs:
        - test
        - dockerize:
            requires:
              - test
        - deploy:
            requires:
              - dockerize

